# -*- coding: utf-8 -*-
"""CropYieldPrediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sGLgNnWHp4Ydh8dXqdT0yqjUMimMQ75S
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
import joblib

# 1. Load and Preprocess Data
print("Loading data...")
crop_data = pd.read_csv('crop_production.csv')

# Handle missing values and feature engineering
crop_data['Production'] = crop_data['Production'].fillna(crop_data['Production'].median())
crop_data['Yield'] = crop_data['Production'] / crop_data['Area']
crop_data['Season'] = crop_data['Season'].str.strip()

# 2. Define and Apply Mappings (Label Encoding)
print("Mapping categorical variables...")
state_mapping = {state: idx for idx, state in enumerate(crop_data['State_Name'].unique())}
district_mapping = {district: idx for idx, district in enumerate(crop_data['District_Name'].unique())}
season_mapping = {season: idx for idx, season in enumerate(crop_data['Season'].unique())}
crop_mapping = {crop: idx for idx, crop in enumerate(crop_data['Crop'].unique())}

crop_data['State_Name'] = crop_data['State_Name'].map(state_mapping)
crop_data['District_Name'] = crop_data['District_Name'].map(district_mapping)
crop_data['Season'] = crop_data['Season'].map(season_mapping)
crop_data['Crop'] = crop_data['Crop'].map(crop_mapping)

# 3. Outlier Handling
def cap_outliers(series):
    lower_limit = series.quantile(0.01)
    upper_limit = series.quantile(0.99)
    return np.clip(series, lower_limit, upper_limit)

crop_data['Area'] = cap_outliers(crop_data['Area'])
crop_data['Yield'] = cap_outliers(crop_data['Yield'])

# 4. Features and Target Selection
X = crop_data[['State_Name', 'District_Name', 'Crop_Year', 'Season', 'Crop', 'Area']]
y = crop_data['Yield']

# 5. Model Training
print("Training model (this may take a moment)...")
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# 6. Evaluation
predictions = model.predict(X_test)
mse = mean_squared_error(y_test, predictions)
r2 = r2_score(y_test, predictions)

print(f"--- Training Complete ---")
print(f"Mean Squared Error: {mse:.4f}")
print(f"R2 Score: {r2:.4f}")

# 7. Saving the Model and Mappings
# We save the mappings so we can reuse them during inference
model_data = {
    'model': model,
    'mappings': {
        'state': state_mapping,
        'district': district_mapping,
        'season': season_mapping,
        'crop': crop_mapping
    }
}

joblib.dump(model_data, 'yield_prediction.pkl')
print("Model and mappings saved to 'yield_prediction.pkl'")

import joblib
import pandas as pd

# 1. Load the bundled model and mappings
bundle = joblib.load('crop_yield_model_bundle.pkl')
model = bundle['model']
mappings = bundle['mappings']

# 2. Define some test samples (Raw text data)
test_samples = [
    {
        'State_Name': 'Karnataka',
        'District_Name': 'BELGAUM',
        'Crop_Year': 2014,
        'Season': 'Kharif',
        'Crop': 'Maize',
        'Area': 1500.0
    },
    {
        'State_Name': 'Uttar Pradesh',
        'District_Name': 'LUCKNOW',
        'Crop_Year': 2015,
        'Season': 'Rabi',
        'Crop': 'Wheat',
        'Area': 2500.0
    }
]

def predict_sample(sample):
    try:
        # Convert the raw text to the numeric codes used during training
        input_data = {
            'State_Name': mappings['state'].get(sample['State_Name']),
            'District_Name': mappings['district'].get(sample['District_Name']),
            'Crop_Year': sample['Crop_Year'],
            'Season': mappings['season'].get(sample['Season']),
            'Crop': mappings['crop'].get(sample['Crop']),
            'Area': sample['Area']
        }

        # Check if any mapping failed (returns None)
        if None in input_data.values():
            return "Error: One of the input labels was not found in the training data."

        # Convert to DataFrame for the model
        input_df = pd.DataFrame([input_data])

        # Predict
        prediction = model.predict(input_df)[0]
        return prediction

    except Exception as e:
        return f"Error: {str(e)}"

# 3. Run the tests
print("--- Model Test Results ---")
for i, sample in enumerate(test_samples):
    result = predict_sample(sample)
    print(f"Sample {i+1} ({sample['Crop']} in {sample['State_Name']}):")
    if isinstance(result, float):
        print(f"Predicted Yield: {result:.2f} units per hectare")
    else:
        print(result)
    print("-" * 30)