# -*- coding: utf-8 -*-
"""PlantDiseaseDetection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UAtdTV9iDYBzao7bby85cMOmxsCvesh7
"""

!nvidia-smi

!pip install ultralytics

from ultralytics import YOLO

!yolo task=detect mode=predict model=yolov8s.pt conf=0.25 source='https://ultralytics.com/images/bus.jpg'

"""Custom Data Training"""

!yolo task=detect mode=train model=yolov8s.pt data=../content/drive/MyDrive/Datasets/PlantDiseases/data.yaml epochs=50 imgsz=640